### ISSUE TITLE
startChat issue

### ISSUE THREAD

**Issue by matheusbortolini** [livechat/livechat-public-docs#255]
TypeError: _this.visitorSDK.startChat is not a function

Error when trying to start a chat using Chat Widget Visitor SDK (https://docs.livechatinc.com/visitor-sdk/#startchat)

Code sample to generate the error:

    this.visitorSDK = init({
      license: <LICENSE>
    })
    this.visitorSDK.startChat().then(data => {
      console.log('data', data)
    })

Command console.log(this.visitorSDK) generate the following:

closeChat:ƒ ()
destroy:ƒ ()
disconnect:ƒ ()
forwardChatTranscript:ƒ ()
getTicketForm:ƒ ()
getVisitorData:ƒ ()
on:ƒ on(type , handler )
rateChat:ƒ ()
sendMessage:ƒ ()
sendTicketForm:ƒ ()
setSneakPeek:ƒ (_ref2)
setVisitorData:ƒ ()
__proto__:Object

But there is no startChat function

**Comment by ale-kacperczyk** [comment]
Since Visitor SDK is now deprecated, we encourage you to use [Customer SDK](https://developers.livechat.com/docs/extending-chat-widget/customer-sdk/).
