### ISSUE TITLE
Chat Button disapearing on mobile while input field focussed

### ISSUE THREAD

**Issue by dblM90** [livechat/livechat-public-docs#263]
Hello,

we have problems using the live chat script on mobile devices. There is a search field on our site. The Button is visible permanently, except when the user taps on the search input field. The div with id livechat-compact-container gets an attribute display:none, when the keyboard opens. But the attribute isn't set to display:block again, when the user presses enter on the keyboard. What is going wrong there?

Best regards,

Merlin

**Comment by ale-kacperczyk** [comment]
Hi @dblM90 👋🏻 It's been a while. I hope you managed to get your problem solved. If not, it sounds like something you can ask our support on the chat as it doesn't seem to be related to our [Platform Documentation](https://developers.livechat.com/docs/).
