### ISSUE TITLE
Unable to send messages consecutively

### ISSUE THREAD

**Issue by ExperLabs** [livechat/livechat-public-docs#272]
We have developed a mobile app in React Native. On Android we often face an issue where chat messages get stuck and the user is unable to send them? We figure out the 'new_message' callback doesn't trigger.

**Comment by ale-kacperczyk** [comment]
Hi @ExperLabs 👋🏻 We have a new SDK for building apps in React Native in case you're still interested. 
Feel free to check it out: https://github.com/livechat/react-native-livechat
