### ISSUE TITLE
Font display

### ISSUE THREAD

**Issue by dimanovoseltsev** [livechat/livechat-public-docs#274]
good day
Add support font-display: for your fonts that are added through the file
https://cdn.livechatinc.com/widget/js/embedded.***.js

Saps https://developers.google.com/speed/pagespeed/insights

Font display - https://developers.google.com/web/updates/2016/02/font-display

**Comment by ale-kacperczyk** [comment]
Hi @dimanovoseltsev 👋🏻

I'm closing the issue since it's now implemented: https://github.com/livechat/livechat-public-docs/blob/a8dd4bb4130d269ee440fce8aaa5259acac8efa1/src/components/core/fonts.css#L7

Sorry for letting you know after so long.
