### ISSUE TITLE
using Mobile Chat Widget for Android App when sending mp3 files

### ISSUE THREAD

**Issue by adriana-devdroid** [livechat/livechat-public-docs#278]
the problem is that when I send mp3 files from the file browser the audios are sent correctly, but if I send them from another route the mp3 files are not sent correctly.Also in huawei devices the app dies when I try to send an mp3.
![device-2018-12-27-153648](https://user-images.githubusercontent.com/10867430/50495211-4a4d7480-09ed-11e9-9f7f-3053b0ccc9e4.png)
![Uploading device
![device-2018-12-27-153446](https://user-images.githubusercontent.com/10867430/50495214-4ae60b00-09ed-11e9-9c7c-0f58595a3e04.png)
-2018-12-27-153541.png…]()
![device-2018-12-27-153523](https://user-images.githubusercontent.com/10867430/50495213-4ae60b00-09ed-11e9-8029-d22be3ac8896.png)

**Comment by adriiiana** [comment]
here I leave the missing screenshots



![device-2018-12-27-153446](https://user-images.githubusercontent.com/10867430/50495344-1f175500-09ee-11e9-9393-055c288575f5.png)
![device-2018-12-27-153541](https://user-images.githubusercontent.com/10867430/50495347-25a5cc80-09ee-11e9-8f66-f6657b4afff1.png)

**Comment by ale-kacperczyk** [comment]
Hi @adriiiana 👋🏻 Do you still encounter this issue?
