### ISSUE TITLE
Unable to see textbox when live chat is clicked

### ISSUE THREAD

**Issue by mitulshah96** [livechat/livechat-public-docs#281]
We have Integrated Live Chat in our app. Since we click on the Live chat the window opens but we don't find any text input appearing.

<img width="321" alt="screen shot 2019-01-11 at 12 12 55 pm" src="https://user-images.githubusercontent.com/29948589/51018525-f1114380-159d-11e9-95a3-9c0b9f4114e7.png">

**Comment by ale-kacperczyk** [comment]
Hi @mitulshah96 👋🏻
Have you managed to solve your problem? It looks like something you should contact our support about. This repository is related to [LiveChat Platform Docs](https://developers.livechat.com/docs/).

**Comment by ale-kacperczyk** [comment]
The issue seems to be outdated. In case of problems with the LiveChat app, please contact our support. For issues related to development, contact us at developers@livechat.com. If you find any bugs, typos, incorrect info in the LiveChat documentation, feel free to open an issue.
