### ISSUE TITLE
Sending file for mobile based applications

### ISSUE THREAD

**Issue by AFGhazy** [livechat/livechat-public-docs#298]
Currently the documentation is misleading about sending files from visitorSDK in the mobile-based apps it should be Object instead of blob, I have created pull request BTW.

**Comment by ale-kacperczyk** [comment]
Hi, I'm closing this issue since VisitorSDK is deprecated. I encourage you to use [CustomerSDK](https://developers.livechat.com/docs/extending-chat-widget/customer-sdk/) instead.
