### ISSUE TITLE
documentation wrong data type

### ISSUE THREAD

**Issue by moeras88** [livechat/livechat-public-docs#299]
https://developers.livechatinc.com/docs/rest-api/#get-list-of-chats says the data type of order price is a string while the api itself returns a numeric type.

**Comment by ale-kacperczyk** [comment]
Since this method is deprecated, we encourage you to switch to our new Messaging APIs and the [List Archives](https://developers.livechat.com/docs/messaging/agent-chat-api/#list-archives) method.
