### ISSUE TITLE
add custom visitor details wrong data type

### ISSUE THREAD

**Issue by moeras88** [livechat/livechat-public-docs#300]
add custom visitor details doesn't work correctly when supplied with an integer license_id (as the example in de docs states). it gives back a 200 status code while in reality it does nothing.

**Comment by ale-kacperczyk** [comment]
I'm closing the issue since `add_custom_visitor_details` is deprecated. I encourage you to use our new [Configuration API](https://developers.livechat.com/docs/management/configuration-api/).
