### ISSUE TITLE
Get active/queued chats list

### ISSUE THREAD

**Issue by dedieudiego** [livechat/livechat-public-docs#303]
I'm trying to build an alike UI that Livechat has for chats section but inside my platform and cannot find the way to get the list of chats that an agent is already part of or the chats that are in queue waiting for an agent to accept it.
Is there a way, and endpoint or somehow that returns me all the chats so I can make a list in order to show it to the agents inside my platform?

**Comment by ale-kacperczyk** [comment]
Hey @dedieudiego! 

I encourage you to check out [Simple Agent](https://developers.livechat.com/docs/messaging/chat-sdk/#simple-agent), which is a demo app that reimplements the basic messaging mechanism with the use of our Chat SDK. You can see exactly how it's done in the code. 

If you want to start from scratch, take a look at the [List Chats](https://developers.livechat.com/docs/messaging/agent-chat-api/v3.3/#list-chats) method. It returns chats with the  `last_thread_summary` object, which contains the `active` parameter and `queue` if the chat's in the queue.

If you find the chat/thread nomenclature confusing, make sure to check out [the article](https://developers.livechat.com/docs/messaging/#chats-and-threads) that explains the difference.
