### ISSUE TITLE
Chatbot/BotEngine Service sends "Bot sent rich message." 

### ISSUE THREAD

**Issue by raihanmasroor** [livechat/livechat-public-docs#307]
When ChatBot workflow has quick replies or other ChatBot features, instead of being displayed in the LiveChat message, LiveChat sends UI a message stating "Bot sent rich message". Visitors are unable to see the chat bot's quick replies. 

Works fine for web integration, but react-native app integrated with LiveChat does not show Chatbot's messages.

**Comment by venits** [comment]
Hi, react-native integration uses [visitor-sdk](https://developers.livechatinc.com/docs/visitor-sdk/#new-message) library which does not support rich messages.

To support rich messages you will have to write your own chat that supports rich messages. To do so you can take a look at on our [Customer-Sdk](https://developers.livechatinc.com/beta-docs/customer-sdk) that has listener for rich messages and all types of events.

**Comment by ale-kacperczyk** [comment]
Hi @raihanmasroor 👋🏻 Since Visitor SDK is already deprecated anyway, you can take a look at [Customer SDK](https://developers.livechat.com/docs/extending-chat-widget/customer-sdk/) and our new [LiveChat for Reach Native library](https://github.com/livechat/react-native-livechat).
