### ISSUE TITLE
using Mobile Chat Widget for Android App Often show “Couldn\'t load chat.”

### ISSUE THREAD

**Issue by Jerrychengjun** [livechat/livechat-public-docs#309]
If I don't use livechat for 2 or 3 minutes in my App，
It will shows "Couldn\'t load chat."

The Website tells me that I can change the error message,But that's not what I need.
[LiveChat Docs](https://developers.livechatinc.com/docs/android-widget/#sample-application)
<string name="failed_to_load_chat">Couldn\'t load chat.</string>

I need to catch exception events，and complete retry function
![livechat_error](https://user-images.githubusercontent.com/49055094/55213874-b4192c80-522f-11e9-888b-6fcbf90c5a65.PNG)

**Comment by ale-kacperczyk** [comment]
Hi @Jerrychengjun 👋🏻 Do you still encounter this problem?
