### ISSUE TITLE
SocketRocket: In debug mode.  Allowing connection to any root cert

### ISSUE THREAD

**Issue by HamzaIkram2727** [livechat/livechat-public-docs#312]
I am using livechat visitor sdk and keep on getting this message on the console. Firstly want to know why this occurs and whats the probable solution for this?. Secondly i am unable to send messages after some time in the chat from the mobile while still receiving messages from the livechat agent side. Does this occur due to the SocketRocket: In debug mode. Allowing connection to any root cert? any help will be appreciated

**Comment by ale-kacperczyk** [comment]
Hi @HamzaIkram2727 👋🏻 I'm closing the issue since VisitorSDK is deprecated. We encourage you to use [CustomerSDK](https://developers.livechat.com/docs/extending-chat-widget/customer-sdk/) instead.
