### ISSUE TITLE
message_seen event only fired for first time

### ISSUE THREAD

**Issue by akhilvasudev-kiwi** [livechat/livechat-public-docs#323]
Hi Team,

      I am using Live chat visitor sdk v 0.35.0. 
      But message_seen event is getting fired for only first time when I send message to an agent.

**Comment by ale-kacperczyk** [comment]
Hi @akhilvasudev-kiwi 👋🏻
I'm closing this issue since VisitorSDK was deprecated. I encourage you to use [CustomerSDK](https://developers.livechat.com/docs/extending-chat-widget/customer-sdk/).
