### ISSUE TITLE
Android SDK connection lost 

### ISSUE THREAD

**Issue by gavotg** [livechat/livechat-public-docs#329]
I can start a chat using the Android SDK fine, but if I exit the app and start a new ChatWindowView with the same configuration instead of loading the existing chat on the Android phone it displays 'Connection lost. Please check internet connection and then try again'

I can reproduce this issue on the sample app.

There seems to be a problem ChatWindowView getting lost and not reseting itself.
This even happens if you're in a chat and rotate the phone it looses the window and there is no way to get out of the Connection lost state.

**Comment by ale-kacperczyk** [comment]
Hi @gavotg 👋🏻 Do you still encounter this problem?

**Comment by gavotg** [comment]
Hi, I'm not using this lib anymore, happy for you to close this.
