### ISSUE TITLE
Custom chatbot integration

### ISSUE THREAD

**Issue by c-charalampous** [livechat/livechat-public-docs#345]
Hello,

I had a talk the other day with the support stuff regarding the integration of custom chatbots with Livechat and human handover when the user or another trigger requires it. I was told it was possible to achieve this with the demo APIs. Can you please guide me through the process of how I would go about doing it? My chatbot is developed with Dialogflow and we have facebook messenger integration.

Thanks in advance

**Comment by hamza-attiq** [comment]
@c-charalampous, Any luck to integrate a custom chatbot?
I'm looking for the same thing.
If yes please share your experience. Thanks

**Comment by ale-kacperczyk** [comment]
Hi @c-charalampous, @hamza-attiq 👋🏻

Some time ago, we ran a [webinar](https://www.youtube.com/watch?v=67oNOUXaHko) that demonstrates how to integrate an AI solution with LiveChat using webhooks. In the webinar, we show you how to connect LiveChat with [ChatBot](https://www.chatbot.com/), but you can apply the general idea to other AI solutions as well.

You can also check out [this article](https://medium.com/cognigyai/connecting-livechat-to-cognigy-ai-enterprise-virtual-agents-using-endpoint-transformers-a4e74d18bc84) about the integration between LiveChat and Cognigy.AI.

If you want to continue the conversation and share your experience with other developers, I encourage you to take the discussion to our [LiveChat Community](https://www.livechat.com/community/).
