### ISSUE TITLE
Why did some of the /visitors endpoints go away?

### ISSUE THREAD

**Issue by jmayhew-oc** [livechat/livechat-public-docs#357]
| Methods       | Path      |	
|--------------|-----------|	
| `POST` | `/visitors/<VISITOR_ID>/chat/start` |	
| `GET` | `/visitors/<VISITOR_ID>/chat/get_pending_messages` |	
| `POST` | `/visitors/<VISITOR_ID>/chat/send_message` |	
| `POST` | `/visitors/<VISITOR_ID>/chat/close` |

Sorry if I'm not submitting this correctly... I'm new to github...

Can anyone comment on why these endpoints were deleted from the documentation? 
https://github.com/livechat/livechat-public-docs/commit/bd64a989098b5e4f710fde700bd0896a14de7058#diff-98defd6ee70dfb1dea416cecdf391f58

Am we now supposed to use another method to have our apps pose as visitors?

Thanks for any info.

**Comment by ale-kacperczyk** [comment]
Hi @jmayhew-oc! Those endpoints were deprecated. I encourage you to migrate to our new [Messaging APIs](https://developers.livechat.com/docs/messaging/):

[Agent Chat API](https://developers.livechat.com/docs/messaging/agent-chat-api/)
[Customer Chat API](https://developers.livechat.com/docs/messaging/customer-chat-api/)
+ [Configuration API](https://developers.livechat.com/docs/management/configuration-api/)
