### ISSUE TITLE
VisitorSDK: Deregister listeners without destroying instance? Or restart instance?

### ISSUE THREAD

**Issue by JedLJRobertson** [livechat/livechat-public-docs#422]
Hey there,

I am having an issue with the VisitorSDK lifecycle. I can delete the livechat with livechat.destroy();, but if I then call livechat = livechatSDK.init() to create a new instance, this new instance is not functional? 

If I don't call livechat.destroy(), then the new instance ends up with double registered listeners.

Is there a better way to be cleaning up/creating the livechat instance? Or should SDK.init() function even after livechat.destroy();

**Comment by ale-kacperczyk** [comment]
Since Visitor SDK is now deprecated, we encourage you to use [Customer SDK](https://developers.livechat.com/docs/extending-chat-widget/customer-sdk/).
