### ISSUE TITLE
HasToken Issue 

### ISSUE THREAD

**Issue by anirban-hazra** [livechat/livechat-public-docs#648]
While authenticating customerSdk, I first checked whether access token exists or not by hasToken method, it returns me false. I have validated the code in a way so that when hasToken promise returns true value, then rest of the start chat code api's will be called. Inspite of that, hasToken promise returns true value but some exception is also throwing simultaneously with unwanted error screen. How I can remove the opening of those error screen?

The error screenshot is here it is, https://cdn-staging.livechat-files.com/api/file/lc/att/1520/e9354595c469ecfce55e91dedaa09a31/Screenshot%20from%202020-05-07%2011-32-58.png

**Comment by klarzynskik** [comment]
Hey @anirban-hazra, thanks for the report!

Could you please share more details with us:

- the version of the `@livechat/customer-sdk`,
- if it's possible, can you share your code with us? If it's not - could you prepare an example of what you are trying to achieve and how e.g. using https://codesandbox.io/?

The reason why I'm asking is that in most cases while using that library, you shouldn't have to worry about the authentication token. The library should handle authentication for you with the built-in `init` method, which for the newest `customer-sdk` (v2.0.0-beta.2) version looks like that:

```js
const customerSDK = CustomerSDK.init({
  licenseId: LICENSE_ID,
  clientId: CLIENT_ID,
})
```

Looking forward to your reply!

**Comment by anirban-hazra** [comment]
LiveChat version is ^2.0.0-alpha.3

**Comment by anirban-hazra** [comment]
I have used following code for authentication & then start chat purpose and if chat is started, then rest of the functions will execute.

customerSDK.auth
        .hasToken()
        .then(token => {
          console.log("hasToken ", token);

          if (token === true) {
            customerSDK.auth
              .getToken()
              .then(token => {
                console.log(token, typeof token, window.token);
                if (token.accessToken !== undefined) {
                  customerSDK.on("connected", payload => {
                    console.log("connected", payload);
                    this.setState({ isLoading: false });
                    if (payload.availability === "online") {
                      //start chat
                      customerSDK
                        .startChat({
                          events: []
                        })
                        .then(chat => {
                          //came for the first time when a chat is active
                          console.log("Start Chat Response ==> ", chat);
                        })
                        .catch(error => {
                          // if already a chat exists, then catch block will inform the dev but
                          // that won't affect any chat functionality.

                          console.log("Start Chat Error ==> ", error);
                        });
                      this.props.navigation.navigate("Message");
                    } else {
                      console.log("Access token is undefined.");
                      this.setState({ errorText: "error", isLoading: false });
                    }
                    // console.log(payload.customer.statistics.chatsCount);
                  });
                } else {
                  this.setState({ errorText: "error", isLoading: false });
                }
              })
              .catch(err => {
                console.log("getFreshToken error");
                this.setState({ errorText: "error", isLoading: false });
                NativeModules.ExceptionsManager = null;
              });
          } else {
            console.log("token not found.");
            this.setState({ errorText: "error", isLoading: false });
            this._authenticateAndStartChat('recursive');
          }
        })
        .catch(err => {
          console.log("hasToken error");
          this.setState({ errorText: "error", isLoading: false });
          // NativeModules.ExceptionsManager = null;
          this._authenticateAndStartChat('recursive');
        });

**Comment by anirban-hazra** [comment]
I have used following code for authentication & then start chat purpose and if chat is started, then rest of the functions will execute.

customerSDK.auth
      .hasToken()
      .then(token => {
        console.log("hasToken ", token);

        if (token === true) {
          customerSDK.auth.getToken().then(token => {

            console.log(token, typeof token, window.token)
            if (token.accessToken !== undefined) {
              customerSDK.on("connected", payload => {
                console.log("connected", payload);
                this.setState({ isLoading: false });
                if (payload.availability === "online") {
                  //start chat
                  customerSDK
                    .startChat({
                      events: []
                    })
                    .then(chat => {
                      //came for the first time when a chat is active
                      console.log("Start Chat Response ==> ", chat);
                    })
                    .catch(error => {
                      // if already a chat exists, then catch block will inform the dev but 
                      // that won't affect any chat functionality.
                      
                      console.log("Start Chat Error ==> ", error);
                    });
                  this.props.navigation.navigate("Message");
                } else {
                  console.log("Access token is undefined.")
                  this.setState({ errorText: "error", isLoading: false });
                }
                // console.log(payload.customer.statistics.chatsCount);
              });
            } else {
              this.setState({ errorText: "error", isLoading: false });
            }
          })
          .catch(err => {
            console.log("getFreshToken error")
            this.setState({ errorText: "error", isLoading: false });
            NativeModules.ExceptionsManager = null;
          });
        } else {
          console.log("token not found.")
          this.setState({ errorText: "error", isLoading: false });
        }
      })
      .catch(err => {
        console.log("hasToken error")
        this.setState({ errorText: "error", isLoading: false });
        NativeModules.ExceptionsManager = null;
      })

**Comment by anirban-hazra** [comment]
@klarzynskik Hope I can get the exact solution

**Comment by klarzynskik** [comment]
Thanks for providing more details!

By looking at your code and your screenshot, it appears that you shouldn’t need to use either `hasToken` or `getToken` methods, even though you use React Native.

In order to authenticate customer in your React Native application, you should use a `AuthWebView` wrapper built in the `customer-auth` package, like that:

```js
import { AuthWebView } from '@livechat/customer-auth'
import { init } from '@livechat/customer-sdk'
export default class App extends React.Component {
  customerSDK = null
  componentDidMount() {
    const customerSDK = init({
    this.customerSDK = init({
      licenseId: LICENSE_ID,
      clientId: CLIENT_ID,
      redirectUri: REDIRECT_URI,
    })
    // you can start using customerSDK from now
  }
  render() {
    return (
      <View>
        <AuthWebView />
      </View>
    )
  }
}
```

This way, the authentication would be handled for you under the hood! You can find more information about that in our docs: https://developers.livechat.com/docs/extending-ui/extending-chat-widget/customer-sdk/#using-the-api-in-react-native

Additionally, we provide a `react-native-livechat` library, which also uses the `customer-sdk`: https://github.com/livechat/react-native-livechat. Perhaps you will find it useful!

Let me know if this won’t work for you or if you have any other questions.

**Comment by anirban-hazra** [comment]
@klarzynskik I tried by not using "hasToken" & "getToken" methods, but for the first time after app being installed, if access token is not found, then I am getting the same error although I have used AuthWebView component in render method. Hope, you can understand the problem & give the solution.

**Comment by klarzynskik** [comment]
>  I am getting the same error although I have used AuthWebView component in render method

Can you please share more details on how you have implemented that?

Additionally, have you considered using the `react-native-livechat` package I've linked in the previous post ([react-native-livechat](https://github.com/livechat/react-native-livechat)) or even simpler, just the Webview to embed LiveChat widget using a direct chat link: [Alternative React Native installation method](https://github.com/livechat/react-native-livechat#alternative-react-native-installation-method)? Both of these methods require less effort and should work with minimal configuration required.

**Comment by anirban-hazra** [comment]
uddenly, by regorous debugging of my code, I found error in line #220 of a node_module in "\node_modules\@livechat\customer-auth\dist\customer-auth.native.js" this path of node_modules directory. Actually some callback is not getting required value. Can you please tell, why is this kind of error is coming & what is its solution?

**Comment by anirban-hazra** [comment]
Suddenly, by regorous debugging of my code, I found error in line #220 of a node_module in "\node_modules\@livechat\customer-auth\dist\customer-auth.native.js" this path of node_modules directory. Actually some callback is not getting required value. Can you please tell, why is this kind of error is coming & what is its solution?

**Comment by klarzynskik** [comment]
> Actually some callback is not getting required value. Can you please tell, why is this kind of error is coming & what is its solution?

Please, could you share more details about the reproduction steps, the actual error you are getting, and if possible, the code snippet of what you're trying to do?

**Comment by anirban-hazra** [comment]
I have one query. According to LiveChat doc & also as per your one of the previous replies, I have to render AuthWebView. But my question is, I have to render my chat with us form also, so how can I render both of AuthWebView (for authentication purpose) & my own UI?

**Comment by anirban-hazra** [comment]
> > Actually some callback is not getting required value. Can you please tell, why is this kind of error is coming & what is its solution?
> 
> Please, could you share more details about the reproduction steps, the actual error you are getting, and if possible, the code snippet of what you're trying to do?

![hasToken issue](https://user-images.githubusercontent.com/53345279/81645478-4934b000-9447-11ea-984a-93683634a558.png)

**Comment by anirban-hazra** [comment]
> > > Actually some callback is not getting required value. Can you please tell, why is this kind of error is coming & what is its solution?
> > 
> > 
> > Please, could you share more details about the reproduction steps, the actual error you are getting, and if possible, the code snippet of what you're trying to do?
> 
> ![hasToken issue](https://user-images.githubusercontent.com/53345279/81645478-4934b000-9447-11ea-984a-93683634a558.png)

This error I am getting when I start chat for the first time ever. Afterwards, the error does not come back. And by debugging of that error, I found the the problem of not getting a value in a callback is occurring at line no. 220 of "\node_modules@livechat\customer-auth\dist\customer-auth.native.js" this file. Can you give me the reason & also solution?

**Comment by anirban-hazra** [comment]
@klarzynskik I have executed the authentication part (by access token) in a blank react native project, installed with only necessary packages of react native & @livechat/customer-sdk package (needed for livechat). But here also, I got the same error of not finding the token - actually, as I have told earlier, when chat page of the app runs for first time, then the "hasToken" method returns false i.e. no token is generated for the first time & during that moment, in mobile screen, a red screen appears, where "TypeError: undefined is not an object (evaluating _ref.callback)" is written. 

I have sending my code of authentication part below:- 

const customerSDK = init({
      license: 11926725, //11926725
      clientId: "b71b22e9d9d019ce72cd5b836ebb27c2", //34eb61d9a416609c4ec41ce45152613f
      redirectUri: "https://www.livechat.com/"
    });
    customerSDK.auth
      .hasToken()
      .then(token => {
        console.log("hasToken ", token);

        if (token) {
          customerSDK.auth.getToken().then(token => {

            console.log(token)
            if (typeof token.accessToken !== undefined) {
              customerSDK.on("connected", payload => {
                console.log("connected", payload);
                this.setState({ isLoading: false });
                if (payload.availability === "online") {
                  //start chat
                  customerSDK
                    .startChat({
                      events: []
                    })
                    .then(chat => {
                      console.log("Start Chat Response ==> ", chat);
                    })
                    .catch(error => {
                      console.log("Start Chat Error ==> ", error);
                    });
                  this.props.navigation.navigate("Message");
                } else {
                  this.setState({ errorText: "error", isLoading: false });
                }
                // console.log(payload.customer.statistics.chatsCount);
              });
            } else {
              this.setState({ errorText: "error", isLoading: false });
              console.log('456789087654324')
            }
          })
          .catch(err => {
            this.setState({ errorText: "error", isLoading: false });
          });
        } else {
          this.setState({ errorText: "error", isLoading: false });
        }
      })
      .catch(err => {
        this.setState({ errorText: "error", isLoading: false });
      })
![Screenshot_20200512-190321_Expo](https://user-images.githubusercontent.com/53345279/81698418-95054a80-9483-11ea-84ab-3b164e339a6c.jpg)


Kindly help me to solve this issue because for this one error, app crashes for the first time during connection of chat page to livechat.

**Comment by anirban-hazra** [comment]
I am found the reason of this error and it is --> the presence of AuthWebView in render although I can't displace it also. So, can you give me the solution of avoiding the error screen coming for this AuthWebView?

**Comment by anirban-hazra** [comment]
Actually 
If error occurs, then 
2. if AuthWebView is not rendered and navigation is fixed to same page, then an error screen does not appear on first attempt alongside not getting tokens although on reload, token has not found suddenly. So, token found on second attempt but an error screen comes on first attempt.
1. if AuthWebView is rendered and navigation is fixed to same page, then an error screen appears and on reload, token is got suddenly. So, token not found on second attempt but an error screen does not come on first attempt.
3. Irrespective of rendering or not rendering AuthWebView, if navigation is done to other page, then error screen will not come again but token will also not found on successive reloads

**Comment by Coder108** [comment]
How does this solve this problem?

**Comment by anirban-hazra** [comment]
> How does this solve this problem?

I don't know. That's why, I am asking.
