### ISSUE TITLE
AuthWebView Error Issue

### ISSUE THREAD

**Issue by anirban-hazra** [livechat/livechat-public-docs#663]
While starting live-chat in mobile app, developed by React Native, if error occurs on the first attempt due to not getting access token, then 
1. if AuthWebView is not rendered and navigation is fixed to same page, then an error screen does not appear on first attempt alongside not getting tokens although on reload, token has not found yet. So, token not found on second attempt despite no error screen comes on first attempt.
2. if AuthWebView is rendered and navigation is fixed to same page, then an error screen appears on first attempt and on reload, token is got suddenly. So, token is found on second attempt after reoading app but an error screen comes on first attempt.
3. Irrespective of rendering or not rendering AuthWebView, if navigation is done to other page, then error screen will not come again but token will also not found on successive reloads.

I have given above three circumstances which I face and from this, I am sure that on first instance, access token is not found and for getting the token I have to reload the app but provided if error comes, AuthWebView should be rendered else on successive reloads even, token will not be found and hence no solution. And if, AuthWebView is rendered, then on a reload token will be found although AuthWebView will throw an error screen on first attempt for not getting error. So, I will be very thankful if you can give the solution about process of getting token at least on second attempt after reload provided no error screen should be thrown for AuthWebView rendering on first attempt for not getting token.

**Comment by ale-kacperczyk** [comment]
Hey @anirban-hazra 👋🏻 Have you managed to solve the issue or is it something you need help with?
