### ISSUE TITLE
Can anyone help me? undefined is not an object....

### ISSUE THREAD

**Issue by Coder108** [livechat/livechat-public-docs#685]
![image](https://user-images.githubusercontent.com/30209569/84743507-a7bff180-afe4-11ea-888f-dd3837a757ca.png)
![image](https://user-images.githubusercontent.com/30209569/84743606-c625ed00-afe4-11ea-963b-b8ec733223dc.png)

import React from 'react';
import {View,StyleSheet} from 'react-native';
import LiveChat from 'react-native-livechat'
export default class App extends React.Component {
    componentDidMount() {
    }

    render() {
        return (
            <View style={{backgroundColor:'#f535',flex:1}}>
                <LiveChat
                    ref={re => {
                        this.liveChat = re
                    }}
                    license={11992980}
                    redirectUri="https://my.livechatinc.com"
                    clientId="59e4900af08ffd29ed76f23b472c81b1"
                    chatTitle={'abc'}
                    greeting={'hello？'}
                    noAgents={'hi!'}
                    bubbleStyles={{
                        position: "absolute",
                        bottom: 12,
                        right: 12,
                    }}
                />
                {/*<AuthWebView style={{backgroundColor:'#0ff3',width:280,height:300}} />*/}
            </View>
        );
    }
}

What is the problem??help me

**Comment by Coder108** [comment]
What is the problem??help me

**Comment by joaohedy** [comment]
The problem lies in the `AuthWebView` component code.

Check: https://github.com/livechat/react-native-livechat/issues/84#issuecomment-734337699
